# Generated by Django 4.2.9 on 2024-08-22 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('participant', 'Participant'), ('organiser', 'Organiser'), ('administrator', 'Administrator')], default='participant', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('max_participants', models.IntegerField()),
                ('rating', models.IntegerField(default=0)),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_signed_up', 'Not Signed Up'), ('signed_up', 'Signed Up')], default='not_signed_up', max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteeringapp.event')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_photo', models.ImageField(upload_to='participant_photos/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('experience_level', models.IntegerField(default=0)),
                ('app_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='volunteeringapp.appuser')),
                ('category_preferences', models.ManyToManyField(blank=True, related_name='participants', to='volunteeringapp.category')),
                ('past_events', models.ManyToManyField(blank=True, related_name='past_participants', to='volunteeringapp.event')),
                ('upcoming_events', models.ManyToManyField(blank=True, related_name='upcoming_participants', through='volunteeringapp.EventParticipation', to='volunteeringapp.event')),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('organization_writeup', models.TextField()),
                ('profile_photo', models.ImageField(upload_to='organizer_photos/')),
                ('organization_email', models.EmailField(max_length=254, unique=True)),
                ('app_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='volunteeringapp.appuser')),
            ],
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteeringapp.participant'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='volunteeringapp.organizer'),
        ),
        migrations.AddField(
            model_name='event',
            name='preference_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='volunteeringapp.category'),
        ),
    ]
