# Generated by Django 4.2.9 on 2024-08-23 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteeringapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='profile_photo',
        ),
    ]
