# Generated by Django 4.2.9 on 2024-08-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteeringapp', '0003_event_signups_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='withdrawals_locked',
            field=models.BooleanField(default=False),
        ),
    ]
