# Generated by Django 4.2.9 on 2024-08-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteeringapp', '0006_chatroom_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='preference_tag',
        ),
        migrations.AddField(
            model_name='event',
            name='preference_tags',
            field=models.ManyToManyField(blank=True, related_name='events', to='volunteeringapp.category'),
        ),
    ]
