# Generated by Django 4.2.9 on 2024-09-01 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteeringapp', '0007_remove_event_preference_tag_event_preference_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organizer',
            new_name='Organiser',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='organizer',
            new_name='organiser',
        ),
        migrations.RenameField(
            model_name='organiser',
            old_name='organization_email',
            new_name='organisation_email',
        ),
        migrations.RenameField(
            model_name='organiser',
            old_name='organization_name',
            new_name='organisation_name',
        ),
        migrations.RenameField(
            model_name='organiser',
            old_name='organization_writeup',
            new_name='organisation_writeup',
        ),
    ]
